info:
  # ç«™ç‚¹æ ‡é¢˜
  title: æ˜Ÿè‹’é¸­ Â· åšå®¢
  # ç«™ç‚¹å‰¯æ ‡é¢˜
  subtitle: xingranya Â· ä¸ªäººåšå®¢ä¸ä½œå“é›†
  # ä½œè€…åç§°
  author: xingranya
  # ç«™ç‚¹ URL
  url: https://xingranya.asia
# åŸºç¡€ä¿¡æ¯ <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# å›¾ç‰‡é…ç½® >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/basic/defaults
defaults:
  # ç½‘ç«™å›¾æ ‡ Favicon
  favicon: /images/favicon.svg
  # ç«™ç‚¹ Logo
  logo: 
  # ç«™ç‚¹å¤´åƒ
  avatar: /images/avatar-0.jpg
# å›¾ç‰‡é…ç½® <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# é¢œè‰²é…ç½® >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/basic/colors
colors:
  # ä¸»è‰²
  primary: "#FFC0CB"
  # è¾…åŠ©è‰²ï¼ˆå¯é€‰ï¼‰
  secondary:
  # é»˜è®¤ä¸»é¢˜æ¨¡å¼åˆå§‹å€¼ï¼ˆä¼šè¢«ç³»ç»Ÿé…è‰²åå¥½è¦†ç›–ï¼‰
  default_mode: light # light, dark
# é¢œè‰²é…ç½® <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# ç«™ç‚¹ä¸ªæ€§åŒ– >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/basic/global
global:
  # è‡ªå®šä¹‰å…¨å±€å­—ä½“
  fonts:
    # ä¸­æ–‡å­—ä½“
    chinese: 
      enable: true # æ˜¯å¦å¯ç”¨è‡ªå®šä¹‰ä¸­æ–‡å­—ä½“
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif" # å­—ä½“æ—
      url: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" # å­—ä½“ CSS é“¾æ¥
    # è‹±æ–‡å­—ä½“
    english: 
      enable: true # æ˜¯å¦å¯ç”¨è‡ªå®šä¹‰è‹±æ–‡å­—ä½“
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif" # å­—ä½“æ—
      url: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" # å­—ä½“ CSS é“¾æ¥
    # è‡ªå®šä¹‰æ ‡é¢˜å­—ä½“ï¼ˆå¯¼èˆªæ ã€ä¾§è¾¹æ ï¼‰
    title:
      enable: true # æ˜¯å¦å¯ç”¨è‡ªå®šä¹‰æ ‡é¢˜å­—ä½“
      family: "'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif" # å­—ä½“æ—
      url: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" # å­—ä½“ CSS é“¾æ¥
  # å†…å®¹æœ€å¤§å®½åº¦
  content_max_width: 1000px
  # ä¾§è¾¹æ å®½åº¦
  sidebar_width: 210px
  # é¼ æ ‡æ‚¬åœæ•ˆæœ
  hover:
    shadow: true # é˜´å½±æ•ˆæœ
    scale: false # ç¼©æ”¾æ•ˆæœ
  # æ»šåŠ¨è¿›åº¦
  scroll_progress:
    bar: false # è¿›åº¦æ¡
    percentage: true # ç™¾åˆ†æ¯”
  # ç½‘ç«™è®¡æ•°å™¨
  website_counter:
    url: https://cn.vercount.one/js # è®¡æ•°å™¨è„šæœ¬ï¼ˆé€šå¸¸æ— éœ€ä¿®æ”¹ï¼‰
    enable: true # æ˜¯å¦å¯ç”¨
    site_pv: true # ç«™ç‚¹ PV
    site_uv: true # ç«™ç‚¹ UV
    post_pv: true # æ–‡ç«  PV
  # æ˜¯å¦å¯ç”¨å•é¡µä½“éªŒï¼ˆä½¿ç”¨ swupï¼Œç±»ä¼¼ pjaxï¼‰
  single_page: true
  # æ˜¯å¦å¯ç”¨é¢„åŠ è½½åŠ¨ç”»
  preloader:
    enable: true
    custom_message: # è‡ªå®šä¹‰æ¶ˆæ¯ï¼Œç•™ç©ºåˆ™æ˜¾ç¤ºç«™ç‚¹æ ‡é¢˜
  # æ˜¯å¦å¯ç”¨ Open Graph
  open_graph:
    enable: true
    image: /images/og.webp  # é»˜è®¤ og:image
    description: æ˜Ÿè‹’é¸­ xingranya Â· ä¸ªäººåšå®¢ä¸ä½œå“é›†
  # Google Analytics åˆ†æ
  google_analytics:
    enable: false # æ˜¯å¦å¯ç”¨ GA
    id:  # Google Analytics æµ‹é‡ ID
# ç«™ç‚¹ä¸ªæ€§åŒ– <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
    

# FONTAWESOME å­—ä½“å›¾æ ‡ >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/basic/fontawesome
fontawesome: # ä¸“ä¸šç‰ˆ v6.2.1
  # æç»†ç‰ˆ
  thin: false
  # ç»†ä½“ç‰ˆ
  light: false
  # åŒé‡è‰²ç‰ˆ
  duotone: false
  # é”åˆ©å®å¿ƒç‰ˆ
  sharp_solid: false
# FONTAWESOME <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# é¦–é¡µæ¨ªå¹… >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/home/home_banner
home_banner:
  # æ˜¯å¦å¯ç”¨é¦–é¡µæ¨ªå¹…
  enable: true
  # æ¨ªå¹…æ ·å¼
  style: fixed # static æˆ– fixed
  # æ¨ªå¹…å›¾ç‰‡
  image: 
    light: /images/main_bg_ligth.jpg # light mode
    dark: /images/main_bg.jpg # dark mode
  # æ¨ªå¹…æ ‡é¢˜
  title: æ˜Ÿè‹’é¸­ Â· åšå®¢
  # æ¨ªå¹…å‰¯æ ‡é¢˜
  subtitle:
    text: ["Hi there ğŸ‘‹, I'm xingranya / æ˜Ÿè‹’é¸­", 'A passionate developer from China']# æ–‡æ¡ˆæ•°ç»„
    hitokoto:  # ä¸€è¨€é…ç½®
      enable: true # æ˜¯å¦å¯ç”¨ä¸€è¨€
      show_author: true # æ˜¯å¦æ˜¾ç¤ºä½œè€…
      api: https://v1.hitokoto.cn # API åœ°å€ï¼Œå¯æ·»åŠ ç±»å‹
    typing_speed: 100 # æ‰“å­—é€Ÿåº¦ (ms)
    backing_speed: 80 # å›é€€é€Ÿåº¦ (ms)
    starting_delay: 500 # å¼€å§‹å»¶è¿Ÿ (ms)
    backing_delay: 1500 # å›é€€å»¶è¿Ÿ (ms)
    loop: true # æ˜¯å¦å¾ªç¯
    smart_backspace: true # æ˜¯å¦æ™ºèƒ½å›é€€
  # æ¨ªå¹…æ–‡æ¡ˆé¢œè‰²
  text_color: 
    light: "#fff" # äº®è‰²æ¨¡å¼
    dark: "#d1d1b6" # æš—è‰²æ¨¡å¼
  # æ–‡æ¡ˆæ ·å¼
  text_style: 
    # æ ‡é¢˜å­—å·
    title_size: 2.8rem
    # å‰¯æ ‡é¢˜å­—å·
    subtitle_size: 1.5rem
    # æ ‡é¢˜ä¸å‰¯æ ‡é¢˜è¡Œé«˜
    line_height: 1.2
  # æ¨ªå¹…è‡ªå®šä¹‰å­—ä½“
  custom_font: 
    # æ˜¯å¦å¯ç”¨
    enable: true
    # å­—ä½“æ—
    family: 
    # å­—ä½“ CSS é“¾æ¥
    url:
  # æ¨ªå¹…ç¤¾äº¤é“¾æ¥
  social_links:
    # æ˜¯å¦å¯ç”¨
    enable: true
    # å±•ç¤ºæ ·å¼
    style: default # default, reverse, center
    # é“¾æ¥
    links:
      github:  https://github.com/xingranya # ä½ çš„ GitHub é“¾æ¥
      instagram: # ä½ çš„ Instagram é“¾æ¥
      zhihu:  # ä½ çš„çŸ¥ä¹ä¸»é¡µ
      # twitter:  https://x.com/TencentCloudEO # ä½ çš„ X(Twitter) é“¾æ¥
      email:  mailto:xingranya@outlook.jp # ä½ çš„é‚®ç®±
      # ...... # å¯ç»§ç»­æ·»åŠ 
    # å¸¦äºŒç»´ç æŠ½å±‰çš„ç¤¾äº¤é“¾æ¥
    qrs:
      weixin:  # ä½ çš„å¾®ä¿¡äºŒç»´ç å›¾ç‰‡
      # ...... # å¯ç»§ç»­æ·»åŠ 
# é¦–é¡µæ¨ªå¹… <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# å¯¼èˆªæ  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/home/navbar
navbar:
  # è‡ªåŠ¨éšè—å¯¼èˆªæ 
  auto_hide: true
  # å¯¼èˆªæ èƒŒæ™¯é¢œè‰²
  color:
    left: "#f78736" # å·¦ä¾§ 
    right: "#367df7"  # å³ä¾§
    transparency: 50 # é€æ˜åº¦ (10-99)
  # å¯¼èˆªæ å®½åº¦ï¼ˆé€šå¸¸æ— éœ€ä¿®æ”¹ï¼‰
  width:
    home: 1200px # é¦–é¡µ
    pages: 1000px # å…¶ä»–é¡µé¢
  # é“¾æ¥
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house # å¯ç•™ç©º
    Archives: 
      path: /archives 
      icon: fa-regular fa-archive # å¯ç•™ç©º
    Github: 
      path: https://github.com/xingranya
      icon: fa-brands fa-github
      # submenus:
      #   Link1: /link1
      #   Link2: /link2
      #   Link3: /link3
    Album: #
      icon: fa-solid fa-image #icon
      path: /masonry/ 
    # Categories: 
    #   icon: fa-solid fa-tags #icon
    #   path: /tags/ #Link
    Projects: 
      path: /projects/
      icon: fa-solid fa-folder-open
    About: 
      path: /about
      icon: fa-solid fa-circle-info
      # submenus:
      #   Me: /about
      #   Github: https://github.com/EvanNotFound/hexo-theme-redefine
      #   Blog: https://ohevan.com
      #   Friends: /friends
    # ...... # you can add more
  # Navbar search (local search). Requires hexo-generator-searchdb (npm i hexo-generator-searchdb). See https://github.com/theme-next/hexo-generator-searchdb
  search:
    # Whether to enable
    enable: false
    # Preload search data when the page loads
    preload: true
# å¯¼èˆªæ  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# é¦–é¡µæ–‡ç« è®¾ç½® >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/home/home
home:
  # ä¾§è¾¹æ è®¾ç½®
  sidebar:
    enable: true # æ˜¯å¦å¯ç”¨ä¾§è¾¹æ 
    position: left # ä½ç½®ï¼šleft, right
    first_item: menu # é¦–é¡¹ï¼šmenu æˆ– info
    announcement: # å…¬å‘Š
    show_on_mobile: true # ç§»åŠ¨ç«¯æŠ½å±‰æ˜¯å¦æ˜¾ç¤º
    links:
      Archives: 
        path: /archives 
        icon: fa-regular fa-archive # can be empty
      # Tags: 
      #   path: /tags 
      #   icon: fa-regular fa-tags # can be empty
      # Categories: 
      #   path: /categories 
      #   icon: fa-regular fa-folder # can be empty
      # ...... # you can add more
  # æ–‡ç« æ—¥æœŸæ ¼å¼
  article_date_format: auto # auto, relative, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss ç­‰
  # æ–‡ç« æ‘˜è¦é•¿åº¦
  excerpt_length: 200 # æœ€å¤§æ‘˜è¦é•¿åº¦
  # åˆ†ç±»å¯è§æ€§
  categories:
    enable: false  # æ˜¯å¦å¯ç”¨
    limit: 3 # æœ€å¤šæ˜¾ç¤ºæ•°é‡
  # æ ‡ç­¾å¯è§æ€§
  tags:
    enable: false  # æ˜¯å¦å¯ç”¨
    limit: 3  # æœ€å¤šæ˜¾ç¤ºæ•°é‡
# é¦–é¡µæ–‡ç« è®¾ç½® <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# æ–‡ç«  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/posts/articles
articles:
  # æ–‡ç« æ ·å¼è®¾ç½®
  style:
    font_size: 16px # å­—å·
    line_height: 1.5 # è¡Œé«˜
    image_border_radius: 14px # å›¾ç‰‡åœ†è§’
    image_alignment: center # å›¾ç‰‡å¯¹é½ï¼šleft, center
    image_caption: false # æ˜¯å¦æ˜¾ç¤ºå›¾ç‰‡æ ‡é¢˜
    link_icon: true # æ˜¯å¦æ˜¾ç¤ºé“¾æ¥å›¾æ ‡
    delete_mask: false # ä¸º <del> æ·»åŠ é®ç½©ï¼Œæ‚¬åœå¯è§
    title_alignment: left # æ ‡é¢˜å¯¹é½ï¼šleft, center
    headings_top_spacing: # å„çº§æ ‡é¢˜ä¸Šè¾¹è·
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  # å­—æ•°ç»Ÿè®¡ï¼ˆéœ€è¦ hexo-wordcountï¼‰https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # æ˜¯å¦å¯ç”¨
    count: true # æ˜¯å¦æ˜¾ç¤ºæ€»å­—æ•°
    min2read: true # æ˜¯å¦æ˜¾ç¤ºé˜…è¯»æ—¶é•¿
  # ä½œè€…æ ‡è¯†
  author_label: 
    enable: false # æ˜¯å¦å¯ç”¨
    auto: false # æ˜¯å¦è‡ªåŠ¨æ·»åŠ ç­‰çº§ï¼ˆLv1/Lv2/...ï¼‰
    list: []
  # ä»£ç å—è®¾ç½®
  code_block:
    copy: true # æ˜¯å¦æ˜¾ç¤ºå¤åˆ¶æŒ‰é’®
    style: mac # mac | simple
    highlight_theme: # highlight.js ä¸»é¢˜
      light: github # äº®è‰²ä¸»é¢˜
      dark: vs2015 # æš—è‰²ä¸»é¢˜
    font: # è‡ªå®šä¹‰å­—ä½“
      enable: false # æ˜¯å¦å¯ç”¨
      family: # å­—ä½“æ—
      url: # å­—ä½“ CSS é“¾æ¥
  # ç›®å½•ï¼ˆTOCï¼‰è®¾ç½®
  toc:
    enable: true # æ˜¯å¦å¯ç”¨
    max_depth: 3 # æ·±åº¦
    number: false # æ˜¯å¦è‡ªåŠ¨ç¼–å·
    expand: true # æ˜¯å¦å±•å¼€
    init_open: true # é»˜è®¤å±•å¼€
  # ç‰ˆæƒå£°æ˜
  copyright:
    enable: true # æ˜¯å¦å¯ç”¨
    default: cc_by_nc_sa # é»˜è®¤åè®®ï¼šcc_by_nc_sa, cc_by_nd, cc_by_nc, cc_by_sa, cc_by, all_rights_reserved, public_domain
  # å›¾ç‰‡æ‡’åŠ è½½
  lazyload: true
  # Pangu.jsï¼ˆä¸­è‹±æ–‡è‡ªåŠ¨åŠ ç©ºæ ¼ï¼‰https://github.com/vinta/pangu.js
  pangu_js: false
  # æ–‡ç« æ¨èï¼ˆéœ€è¦ nodejiebaï¼Œç§»æ¤è‡ª volantisï¼‰
  recommendation:
    # æ˜¯å¦å¯ç”¨
    enable: false
    # æ¨èæ ‡é¢˜
    title: Recommended Reading
    # æœ€å¤§æ•°é‡
    limit: 3
    # ç§»åŠ¨ç«¯æœ€å¤§æ•°é‡
    mobile_limit: 2
    # å ä½å›¾
    placeholder: /images/wallhaven-wqery6-light.webp
    # è·³è¿‡ç›®å½•
    skip_dirs: []
# æ–‡ç«  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

effects: 
  particles: true
  cursoreffects: true


# è¯„è®º >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/posts/comment
comment:
  # æ˜¯å¦å¯ç”¨è¯„è®º
  enable: false
  # è¯„è®ºç³»ç»Ÿ
  system: waline # waline, gitalk, twikoo, giscus
  # ç³»ç»Ÿé…ç½®
  config:
    # Waline comment system. See https://waline.js.org/
    waline:
      serverUrl: https://ifpx3kuv.api.lncldglobal.com # Waline æœåŠ¡åœ°å€ï¼Œä¾‹å¦‚ https://example.example.com
      lang: en-US # Waline è¯­è¨€ï¼Œå¦‚ zh-CN, en-US
      emoji: [] # Waline è¡¨æƒ…
      recaptchaV3Key: # Google reCAPTCHA v3 å¯†é’¥
      turnstileKey: # Turnstile å¯†é’¥
      reaction: false # Waline è¡¨æƒ…åé¦ˆ
    # Gitalk comment system. See https://github.com/gitalk/gitalk
    gitalk:
      clientID: # GitHub Application Client ID
      clientSecret: # GitHub Application Client Secret
      repo: # GitHub repository
      owner: # GitHub repository owner
      proxy: # GitHub repository proxy
    # Twikoo comment system. See https://twikoo.js.org/
    twikoo:
      version: 1.6.10 # Twikoo ç‰ˆæœ¬ï¼Œä¸æ¸…æ¥šè¯·å‹¿ä¿®æ”¹
      server_url: # Twikoo æœåŠ¡åœ°å€ï¼Œä¾‹å¦‚ https://example.example.com
      region: # Twikoo åŒºåŸŸï¼Œå¯ä¸ºç©º
    # Giscus comment system. See https://giscus.app/
    giscus:
      repo: # GitHub ä»“åº“ï¼Œä¾‹ï¼šEvanNotFound/hexo-theme-redefine
      repo_id: # GitHub ä»“åº“ ID
      category: # GitHub è®¨è®ºåˆ†ç±»
      category_id: # GitHub è®¨è®ºåˆ†ç±» ID
      mapping: pathname # é¡µé¢å”¯ä¸€æ ‡è¯†ï¼špathname, url, title, og:titleã€‚å¯ç”¨ PJAX æ—¶å‹¿ç”¨ og:title
      strict: 0 # ä¸¥æ ¼æ¨¡å¼ï¼š0, 1
      reactions_enabled: 1 # è¡¨æƒ…ï¼š0, 1
      emit_metadata: 0 # è¾“å‡ºå…ƒæ•°æ®ï¼š0, 1
      lang: en # è¯­è¨€ï¼šen, zh-CN, zh-TW
      input_position: bottom # è¯„è®ºæ¡†ä½ç½®ï¼štop, bottom
      loading: lazy # æ‡’åŠ è½½
# è¯„è®º <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# é¡µè„š >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/footer
footer:
  # å±•ç¤ºç½‘ç«™è¿è¡Œæ—¶é—´
  runtime: true # æ˜¯å¦æ˜¾ç¤º
  # é¡µè„šå›¾æ ‡ï¼ˆFontAwesome ä»£ç ï¼‰
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  # ç½‘ç«™å¼€å§‹æ—¶é—´ï¼Œæ ¼å¼ï¼šYYYY/MM/DD HH:mm:ss
  start: 2022/8/17 11:45:14
  # ç«™ç‚¹ç»Ÿè®¡
  statistics: true # æ˜¯å¦æ˜¾ç¤ºï¼ˆæ–‡ç« æ€»æ•°ã€æ€»å­—æ•°ï¼‰
  # è‡ªå®šä¹‰é¡µè„šæ–‡æ¡ˆ
  customize:
  # ICP å¤‡æ¡ˆå·ï¼šhttps://beian.miit.gov.cn/
  icp:
    enable: true # Whether to enable
    number: å¤‡æ¡ˆå·ï¼šå¾…å¤‡æ¡ˆï¼ˆæ¹–åŒ—Â·åå °ï¼‰ # ICP record number
    url: https://beian.miit.gov.cn/ # ICP record url
# FOOTER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# è‡ªå®šä¹‰æ³¨å…¥ >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/inject
inject:
  # æ˜¯å¦å¯ç”¨æ³¨å…¥
  enable: false
  # æ³¨å…¥è‡ªå®šä¹‰ head HTML
  head: 
    -
    -
  # æ³¨å…¥è‡ªå®šä¹‰ footer HTML
  footer:
    -
    -
# è‡ªå®šä¹‰æ³¨å…¥ <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# æ’ä»¶ >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/plugins
plugins:
  # RSS è®¢é˜…ï¼ˆéœ€è¦ hexo-generator-feedï¼‰ã€‚https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: false # æ˜¯å¦å¯ç”¨
  # Aplayer éŸ³ä¹æ’­æ”¾å™¨ï¼šhttps://github.com/DIYgod/APlayer
  aplayer:
    enable: false # æ˜¯å¦å¯ç”¨
    type: fixed # fixed, mini
    audios:
      - name: # audio name
        artist: # audio artist
        url: # audio url
        cover: # audio cover url
        lrc: # audio cover lrc
#      - name: # audio name
#        artist: # audio artist
#        url: # audio url
#        cover: # audio cover url
#        lrc: # audio cover lrc
      # .... you can add more audios here
  # Mermaid JSï¼ˆéœ€è¦ hexo-filter-mermaid-diagramsï¼‰ã€‚https://mermaid.js.org/
  mermaid:
    enable: false # æ˜¯å¦å¯ç”¨
    version: "11.4.1" # é»˜è®¤ v11.4.1
# æ’ä»¶ <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# é¡µé¢æ¨¡æ¿ >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/page_templates
page_templates:
  # å‹æƒ…é“¾æ¥é¡µåˆ—æ•°
  friends_column: 3
  # æ ‡ç­¾é¡µæ ·å¼
  tags_style: blur # blur, cloud
# é¡µé¢æ¨¡æ¿ <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/cdn
cdn:
  # æ˜¯å¦å¯ç”¨ CDN
  enable: false
  # CDN æä¾›å•†
  provider: npmmirror # npmmirror, zstatic, cdnjs, jsdelivr, unpkg, custom
  # è‡ªå®šä¹‰ CDN URL
  # ç¤ºä¾‹: https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
  # å…¶ä¸­ ${path} å¿…é¡»æŒ‡å‘ä¸»é¢˜çš„ source æ ¹ç›®å½•
  custom_url: 
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# å¼€å‘è€…æ¨¡å¼ >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# æ–‡æ¡£: https://redefine-docs.ohevan.com/developer
developer:
  # æ˜¯å¦å¯ç”¨å¼€å‘è€…æ¨¡å¼ï¼ˆä»…ä¸»é¢˜å¼€å‘è€…ä½¿ç”¨ï¼Œæ™®é€šç”¨æˆ·å‹¿å¼€ï¼‰
  enable: false
# å¼€å‘è€…æ¨¡å¼ <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
